apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    k8s-app: fluentd-logging
    version: v0.6
  name: fluentd-cloudwatch-logs
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v0.6
    spec:
      containers:
        - name: fluentd-cloudwatch-logs
          env:
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: fluentd-cloudwatch-logs
                  key: aws-region
          image: quay.io/widen/fluentd-k8s-cloudwatch-logs:v0.6
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: config-volume
              mountPath: /etc/td-agent
            - name: containers-volume
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: log-volume
              mountPath: /var/log
      hostNetwork: true
      terminationGracePeriodSeconds: 30
      volumes:
        - name: config-volume
          configMap:
            name: fluentd-cloudwatch-logs
            items:
              - key: td-agent-config
                path: td-agent.conf
        - name: containers-volume
          hostPath:
            path: /var/lib/docker/containers
        - name: log-volume
          hostPath:
            path: /var/log
